#Port
Server:
  port: 29102

#Spring Config
spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static

#Jodconverter Configuration
jodconverter:
  local:
    enabled: true
    officeHome: D:/OpenOffice
    portNumbers: 18100
    maxTasksPerProcess: 10